services:
  hello-world:
    image: hello-world
    restart: unless-stopped
    networks:
      starr:
        ipv4_address: 172.20.0.14

networks:
  starr:
    driver: bridge
    name: starr
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/28 # IP range for the network
          gateway: 172.20.0.1
