services:
  qbittorrent-nox:
    # for debugging
    #cap_add:
    #- SYS_PTRACE
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      #- PAGID=10000
      - PUID=${PUID}
      - PGID=${PGID}
      - QBT_LEGAL_NOTICE=confirm
      - QBT_VERSION=latest
      - QBT_WEBUI_PORT=8080
      - TZ=${TZ}
      #- UMASK=022
    image: qbittorrentofficial/qbittorrent-nox:latest
    ports:
      # for bittorrent traffic
      - ${IP}:62418:62418/tcp
      - ${IP}:62418:62418/udp
      # for WebUI
      - ${IP}:8080:8080
    #read_only: true Causes bug with the image see wiki
    stop_grace_period: 1m
    tmpfs:
      - ${BASE_PATH}/qbittorent/tmp
    #tty: true
    volumes:
      - ${BASE_PATH}/qbittorent/config:/config
      - ${MEDIA_SHARE}:/data
    networks:
      - starr

networks:
  starr:
    name: starr
