services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../qbit/compose.yml:/wud/qbit.yml
      - ../arrstack/compose.yml:/wud/arrstack.yml
      - ../portainer/compose.yaml:/wud/portainer.yml
      - ./compose.yaml:/wud/wud.yml
    ports:
      - 3000:3000
    environment:
      - WUD_TRIGGER_DOCKERCOMPOSE_qBittorent_FILE=/wud/qbit.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_qBittorent_PRUNE=true
      - WUD_TRIGGER_DOCKERCOMPOSE_arrstack_FILE=/wud/arrstack.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_arrstack_PRUNE=true
      - WUD_TRIGGER_DOCKERCOMPOSE_portainer_FILE=/wud/portainer.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_portainer_PRUNE=true
      - WUD_TRIGGER_DOCKERCOMPOSE_wud_FILE=/wud/wud.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_wud_PRUNE=true
      - WUD_TRIGGER_GOTIFY_ST_URL=${GOTIFY_URL}
      - WUD_TRIGGER_GOTIFY_ST_TOKEN=${GOTIFY_ST}
      - WUD_TRIGGER_GOTIFY_PN_URL=${GOTIFY_URL}
      - WUD_TRIGGER_GOTIFY_PN_TOKEN=${GOTIFY_PN}
      - WUD_REGISTRY_LSCR_PRIVATE_USERNAME=${LSCR_Username}
      - WUD_REGISTRY_LSCR_PRIVATE_TOKEN=${LSCR_Token}
      - WUD_REGISTRY_GHCR_PRIVATE_USERNAME=${GHCR_Username}
      - WUD_REGISTRY_GHCR_PRIVATE_TOKEN=${GHCR_Token}
      - WUD_REGISTRY_HUB_PUBLIC_LOGIN=${HUB_Username}
      - WUD_REGISTRY_HUB_PUBLIC_TOKEN=${HUB_Token}
      - WUD_AUTH_BASIC_WUD_USER=${WUD_Username}
      - WUD_AUTH_BASIC_WUD_HASH=${WUD_Hass}
      - WUD_WATCHER_LOCAL_CRON=15 06 */8 * *
      - TZ=${TZ}
      
