---
services:
  #Radarr - used to find movies automatically
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/radarr/config:/config
      - ${MEDIA_SHARE}:/data #Access to the entire /media
    ports:
      - ${IP}:7878:7878
    networks:
      - starr
    restart: unless-stopped

  #Sonarr - used to find shows automatically
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/sonarr/config:/config
      - ${MEDIA_SHARE}:/data #Access to the entire /media
    ports:
      - ${IP}:8989:8989
    networks:
      - starr
    restart: unless-stopped

  #Lidarr - Used to download music
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/lidarr/config:/config
      - ${MEDIA_SHARE}:/data
    ports:
      - ${IP}:8686:8686
    networks:
      - starr
    restart: unless-stopped

  #Prowlarr - manages your Sonarr, Radarr and download client
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/prowlarr/config:/config
    ports:
      - ${IP}:9696:9696
    networks:
      - starr
    restart: unless-stopped

  #jellyseer - allows users to request media on their own
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/jellyseerr/config:/app/config
      - ${MEDIA_SHARE}:/data #Access to the entire ${BASE_PATH}
    networks:
      - starr
    ports:
      - ${IP}:5055:5055
    restart: unless-stopped

  #Bazarr - for subtitles. Try to use SRT format if you can rather than PGS due to performance issues
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/bazarr/config:/config
      - ${MEDIA_SHARE}:/data
    ports:
      - ${IP}:6767:6767
    networks:
      - starr

  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - SECRET_ENCRYPTION_KEY=${SECRET_HOMARR}
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${BASE_PATH}/homarr/appdata:/appdata
    ports:
      - ${IP}:80:7575
    networks:
      - starr

  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DOWNLOAD_DIR=/downloads/video
      - AUDIO_DOWNLOAD_DIR=/downloads/audio
      - DELETE_FILE_ON_TRASHCAN=true # Set to false if you want to keep the file in the download folder
    ports:
      - "8081:8081"
    volumes:
      - ${MEDIA_SHARE}/ytd:/downloads

  # #Unpacker - Used to unzip zipped files
  # unpackerr:
  #   image: ghcr.io/hotio/unpackerr:latest
  #   container_name: unpackerr
  #   volumes:
  #     # You need at least this one volume mapped so Unpackerr can find your files to extract.
  #     # Make sure this matches your Starr apps; the folder mount (/downloads or /data) should be identical.
  #     - ${MEDIA_SHARE}:/data
  #     - ${BASE_PATH}/unpackerr/config:/config
  #   restart: unless-stopped
  #   # What you see below are defaults for this compose. You only need to modify things specific to your environment.
  #   # Remove apps and feature configs you do not use or need.
  #   # ie. Remove all lines that begin with UN_CMDHOOK, UN_WEBHOOK, UN_FOLDER, UN_WEBSERVER, and other apps you do not use.
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - UN_START_DELAY=1m
  #     - UMASK=002
  #     - TZ=${TZ}
  #     #- UN_DEBUG=true
  #     # Sonarr Config
  #     - UN_SONARR_0_URL=http://sonarr:8989
  #     - UN_SONARR_0_API_KEY=${SONARR_KEY}
  #     #- UN_SONARR_0_PATHS_0=/${BASE_PATH}/downloads/shows
  #     - UN_SONARR_0_TIMEOUT=10s
  #     #- UN_SONARR_0_PATHS_0=/${BASE_PATH}/downloads/shows
  #     # Radarr Config
  #     - UN_RADARR_0_URL=http://radarr:7878
  #     - UN_RADARR_0_API_KEY=${RADARR_KEY}
  #     #- UN_RADARR_0_PATHS_0=/${BASE_PATH}/downloads/movies
  #     - UN_RADARR_0_TIMEOUT=10s
  #     #- UN_RADARR_0_PATHS_0=/${BASE_PATH}/downloads/movies
  #   networks:
  #     - starr

  # decluttarr:
  #   image: ghcr.io/manimatter/decluttarr:latest
  #   container_name: decluttarr
  #   restart: unless-stopped
  #   environment:
  #     TZ: ${TZ}
  #     PUID: ${PUID}
  #     PGID: ${PGID}
  #     ## General
  #     # TEST_RUN=True
  #     # SSL_VERIFICATION=False
  #     LOG_LEVEL: INFO
  #     ## Features
  #     REMOVE_TIMER: 10
  #     REMOVE_FAILED: True
  #     REMOVE_FAILED_IMPORTS: True
  #     REMOVE_METADATA_MISSING: True
  #     REMOVE_MISSING_FILES: True
  #     REMOVE_ORPHANS: True
  #     REMOVE_SLOW: True
  #     REMOVE_STALLED: True
  #     REMOVE_UNMONITORED: True
  #     RUN_PERIODIC_RESCANS: '
  #       {
  #       "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7},
  #       "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7}
  #       }'
  #     # Feature Settings
  #     PERMITTED_ATTEMPTS: 3
  #     NO_STALLED_REMOVAL_QBIT_TAG: Don't Kill
  #     MIN_DOWNLOAD_SPEED: 100
  #     FAILED_IMPORT_MESSAGE_PATTERNS: '
  #       [
  #       "Not a Custom Format upgrade for existing",
  #       "Not an upgrade for existing"
  #       ]'
  #     ## Radarr
  #     RADARR_URL: http://radarr:7878
  #     RADARR_KEY: $RADARR_KEY
  #     ## Sonarr
  #     SONARR_URL: http://sonarr:8989
  #     SONARR_KEY: $SONARR_KEY
  #     ## Lidarr
  #     LIDARR_URL: http://lidarr:8686
  #     LIDARR_KEY: $LIDARR_KEY
  #     ## Readarr
  #     READARR_URL: http://readarr:8787
  #     READARR_KEY: $READARR_KEY
  #     ## qBitorrent
  #     QBITTORRENT_URL: http://qbittorrent:8080
  #     QBITTORRENT_USERNAME: $QBIT_USER
  #     QBITTORRENT_PASSWORD: $QBIT_PASS
  #   networks:
  #     - starr

networks:
  starr:
    external: true
