services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - ${IP}:9000:9000 # Portainer UI (HTTP)
      #- "9443:9443"   # Portainer UI (HTTPS)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE_PATH}/portainer:/data
